---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sumikiru.
--- DateTime: 2025/7/20 16:52
---

local M = {}
local PrintString = UE.UKismetSystemLibrary.PrintString

function M.PrintToScreen(text, color, duration)
    -- or使得函数参数color和duration可以不填(nil)，不填的话即为默认值UE.FLinearColor(0, 0, 1, 1)和100
    color = color or UE.FLinearColor(0, 0, 1, 1)
    duration = duration or 100
    PrintString(nil, text, true, false, color, duration)
end

return M
